Fix uppercase `L` in BuffLog namespace
bufferapp/php-bufflog pull request #23
Opened 2021-02-02 23:24 UTC by hamstu

Fix a subtle, but improper letter case.

This might be why we couldn't use --classmap-authoritative when dumping the autolaod, as it would conflict with the declared namespace.

2021-03-09 19:49 UTC, erickhun requested changes
good catch @hamstu 

Do you think [we can we also change the composer version](https://github.com/bufferapp/php-bufflog/blob/fix-case/composer.json#L4) so it won't create issues with other services using the library?

I'll need to [deploy the new version to packager](https://packagist.org/packages/bufferapp/php-bufflog) once you merge it too

2021-03-09 19:55 UTC, hamstu commented
Thanks Eric! Good catch on the version. I'll push up that change.

2021-03-09 19:57 UTC, hamstu commented
@erickhun I bumped the minor version. Are you able to take care of deploying it?

2021-03-09 20:09 UTC, erickhun approved these changes
thanks @hamstu I'll deploy this one tomorrow on packagist  - will let you know when it's done

2021-03-09 20:26 UTC, hamstu commented
cc @josem

2021-03-09 23:17 UTC, merged

2021-03-10 08:42 UTC, josem commented
Ah nice, thanks so much for this! :rocket:

2021-03-10 21:25 UTC, erickhun commented
@hamstu  @josem  I've just published it in packagist: https://packagist.org/packages/bufferapp/php-bufflog#0.2.0 !